version: '2'
services:
  web:
    build: . 
    expose:
      - 5000
    environment:
      - VIRTUAL_HOST=whoamiflask.local
      - VIRTUAL_PORT=5000
    volumes:
      - ./server.py:/src/server.py
  nginx:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
